### ISSUE TITLE
bearerTokenSecret not propagated to Service Monitor

### ISSUE THREAD

**Issue by awisniew90** [OpenLiberty/open-liberty-operator#157]
### What did you do?

Configuring `bearerTokenSecret` on the deployment's monitoring endpoint does not propagate to the created Service Monitor.

app-deploy.yaml:
```yaml
monitoring:
    endpoints:
    - bearerTokenSecret:
        key: token
        name: my-test-token-token-v2ktw
      interval: 5s
      tlsConfig:
        insecureSkipVerify: true
    labels:
      app-monitoring: ""
```

Resulting Service Monitor:
```yaml
spec:
  endpoints:
    - bearerTokenSecret:
        key: ''
      interval: 5s
      port: 9080-tcp
      tlsConfig:
        ca: {}
        cert: {}
        insecureSkipVerify: true
```

### What did you expect to see?

The generated service monitor should contain the bearerTokenSecret defined in the deployment.

### What did you see instead?

The `bearerTokenSecret` configuration is not propagated to the service monitor due to the property missing from [servicemonitor.crd.yaml]( https://github.com/OpenLiberty/open-liberty-operator/blob/master/scripts/servicemonitor.crd.yaml )

### Environment

* Kubernetes version information:

1.16.2

* OpenShift version information (if applicable):

Client Version: 4.3.5
Server Version: 4.3.0
Kubernetes Version: v1.16.2

* Appsody CLI version (if applicable):

0.6.1

* Appsody Stack (if applicable):

java-openliberty

### Possible solution

Adding the bearerTokenSecret config to servicemonitor.crd.yaml
