### ISSUE TITLE
Apply service.annotations to the pod

### ISSUE THREAD

**Issue by NottyCode** [OpenLiberty/open-liberty-operator#201]
## Feature Request
Apply service.annotations to the pod. An alternative attribute like pod.annotations could also work.

### Is your feature request related to a problem?

We have a customer wanting to deploy Liberty on Kube and wants to track deployments by annotations applied to the pod. The annotations would effectively say "Liberty is deployed here". The operator does not currently apply annotations to the pod when Liberty is deployed. 

### Describe the solution you'd like

Apply service.annotations to the pod. An alternative attribute like pod.annotations could also work.

**Comment by leochr** [comment]
@NottyCode The annotations added to CR metadata is propagated to all the resources that the operator creates, including pods. It seems that could be used (instead of `service.annotations`, which is only applied to the `Service` resource)

```yaml
apiVersion: openliberty.io/v1beta1
kind: OpenLibertyApplication
metadata:
  name: my-liberty-app
  annotations:
    my-annotation-key: my-annotation-value
```
More information is here (applies to Runtime Component as well as Open Liberty application):
https://github.com/application-stacks/runtime-component-operator/blob/master/doc/user-guide.adoc#annotations
