### ISSUE TITLE
Azure openshift (ARO) Open liberty operator - Application image name issue invalid resource name  [may not contain'/']  

### ISSUE THREAD

**Issue by dpk01** [OpenLiberty/open-liberty-operator#321]
Hi,

We are using open liberty operator on Azure managed Openshif (ARO). Recently we updated the kubernetes version to 1.22 and current openshift version is 4.9. After upgrate we got to know that now channel in operaor is changed to beta2 from beta1. After changing the channle we startd getting below error : 
**invalid resource name "docker_registry/ol-todo:0.5.4": [may not contain'/']**

**application yaml :** 
apiVersion: apps.openliberty.io/v1beta2
kind: OpenLibertyApplication
metadata:
  name: test
  namespace: test
spec:
  pullSecret: secret
  replicas: 1
  applicationImage: >-
    **localhost4:32121/root/docker_registry/ol-todo:0.5.4**

It seems, in the applicationImage it is expecting only one "/" as when we provide value as **localhost4:32121/root/ol-todo:0.5.4**, error changed to image pull back issue as image is not present. However in beta1 it is working as is with full name path   **localhost4:32121/root/docker_registry/ol-todo:0.5.4**.

Is there any change in spec afer beta2 upgrade for application image path ?
We need a quick help here as we are blocked as we have used it for client project.

**Comment by leochr** [comment]
@dpk01 This occurs only when the value of `applicationImage` field contains 3 or more `/`. The issue is within the logic around ImageStream support. We'll fix it. But the fix, as well as the Operator Hub release containing the fix, may take time and we don't have an ETA at this time.

The issue can be avoided if an image value with 2 or less `/` is used. If that's not possible, suggest the following workaround:
1.  Create an ImageStream that points to the image. It can be created in one of two ways. 
    * using CLI. Execute in the same namespace as OpenLibertyApplication instance: `oc tag localhost4:32121/root/docker_registry/ol-todo:0.5.4 ol-todo:prod`
    
    * or create an ImageStream custom resource:

        ```
        apiVersion: image.openshift.io/v1
        kind: ImageStream
        metadata:
          name: imagestream-example
          namespace: test
        spec:
          tags:
          - from:
              kind: DockerImage
              name: localhost4:32121/root/docker_registry/ol-todo:0.5.4
            name: prod
        ```
2.  Specify the ImageStream value in OpenLibertyApplication:
`applicationImage: ol-todo:prod`
