### ISSUE TITLE
Setting serviceAccountName to the default causes the service account to be deleted

### ISSUE THREAD

**Issue by NottyCode** [OpenLiberty/open-liberty-operator#433]
### What did you do?

I created a service account whose name happened to match exactly the default. When I did this the service account was deleted which caused the deploy to fail because it didn't exist.

### What did you expect to see?

I expected it to work:

```
apiVersion: apps.openliberty.io/v1
kind: OpenLibertyApplication
metadata:
  name: openliberty-app-sample-instanton
  namespace: myns
spec:
  securityContext:
    capabilities:
      add:
        - CHECKPOINT_RESTORE
        - SETPCAP
    runAsUser: 1001
  applicationImage: >-
    default-route-openshift-image-registry.apps.alasdair.cp.fyre.ibm.com/myns/getting-started-instanton
  expose: true
  manageTLS: true
  replicas: 1
  serviceAccountName: openliberty-app-sample-instanton
```

### What did you see instead?

The application failed to start because the service account didn't exist

### Environment

* OpenShift version information (if applicable):

```
Client Version: 4.13.0-202304190216.p0.g92b1a3d.assembly.stream-92b1a3d
Kustomize Version: v4.5.7
Server Version: 4.13.0
Kubernetes Version: v1.26.3+b404935
```
