### ISSUE TITLE
Add operator image to relatedImages 

### ISSUE THREAD

**Issue by leochr** [OpenLiberty/open-liberty-operator#448]
The Red Hat CI/CD process now requires all images used in ClusterServiceVersion (CSV) to be added to the `.spec.relatedImages` in CSV. We need to add the operator image to this (in addition to the liberty sample app).

For example:
```
  maturity: stable
  provider:
    name: IBM
  relatedImages:
  - image: icr.io/appcafe/open-liberty/samples/getting-started@sha256:d3c67c4a15c97b0fb82f9ef4a2ccf474232b878787e9eea39af75a3ac78469e3
    name: liberty-sample-app
  - image: icr.io/appcafe/open-liberty-operator@sha256:0ca8db3387280836cb489b71a29628c2f5594ad7ea650496a56d833c1d6827d6
    name: open-liberty-operator
```

- [ ] Delivered to OLO
- [ ] Delivered to RCO
- [x] Delivered to WLO
