### ISSUE TITLE
Set insecureEdgeTerminationPolicy when termination policy is not set in CR

### ISSUE THREAD

**Issue by leochr** [OpenLiberty/open-liberty-operator#463]
insecureEdgeTerminationPolicy setting is not respected when CR is configured with:

```
manageTLS: true
route:
    host: myhost
    insecureEdgeTerminationPolicy: redirect
```

The `insecureEdgeTerminationPolicy` is only respected when `termination` value is also specified under the `route` configuration.

- [x] RCO
- [x] OLO
- [x] WLO
- [x] tests
