### ISSUE TITLE
Allow user to set environment variables for Semeru Cloud Compiler

### ISSUE THREAD

**Issue by mpirvu** [OpenLiberty/open-liberty-operator#555]
### Is your feature request related to a generic (non-Open Liberty) problem?
No

### Is your feature request related to a problem?
No

### Describe the solution you'd like
Currently, a user does not have the possibility of setting options for the Semeru Cloud Compiler deployed by OLO (these options are decided by the Operator internally). To facilitate problem determination, as well as fine tuning for the Semeru Cloud Compiler, it would be best if the user can specify additional environment variables for the Semeru Cloud Compiler deployed by OLO.
E.g.
```
  semeruCloudCompiler:
    enable: true
    replicas: 1
    env:
      - name: _JAVA_OPTIONS
        value: "-Xjit:verbose"
```
