### ISSUE TITLE
Can we avoid topology-aware routing annotations being added to services?

### ISSUE THREAD

**Issue by hhue13** [OpenLiberty/open-liberty-operator#679]
## Type of question

Configuration of Open Liberty operator

### What did you do?

Starting with #497 the Open Liberty operator annotates the Service CR with the annotation to enable tolopogy-aware routing. I.e. the following annotations are set:
```
metadata:
  annotations:
    service.kubernetes.io/topology-aware-hints: Auto
    service.kubernetes.io/topology-mode: Auto
```
This however cases the following events being fired repeatedly in our environment:

> TopologyAwareHintsDisabled Insufficient Node information: allocatable CPU or zone not specified on one or more nodes, addressType: IPv4

### What did you expect to see?

Service CR created by the Open Liberty operator *not* being annotated with ` service.kubernetes.io/topology-aware-hints` and `service.kubernetes.io/topology-mode` 

### What did you see instead? Under which circumstances?

Service CR created by the Open Liberty operator is annotated with:
```
metadata:
  annotations:
    service.kubernetes.io/topology-aware-hints: Auto
    service.kubernetes.io/topology-mode: Auto
```

### Environment

* Kubernetes version information:
```
clientVersion:
  buildDate: "2024-11-04T03:05:04Z"
  compiler: gc
  gitCommit: d691257345aeeec951c763e11658a944037f9b39
  gitTreeState: clean
  gitVersion: v1.25.2
  goVersion: go1.19.13 X:strictfipsruntime
  major: "1"
  minor: "25"
  platform: linux/amd64
kustomizeVersion: v4.5.7
serverVersion:
  buildDate: "2024-09-25T18:21:27Z"
  compiler: gc
  gitCommit: 4c2e25b907743906b0b4cbb269d8f8edfab24a6e
  gitTreeState: clean
  gitVersion: v1.29.8+632b078
  goVersion: go1.21.13 (Red Hat 1.21.13-5.el9_4) X:strictfipsruntime
  major: "1"
  minor: "29"
  platform: linux/amd64

WARNING: version difference between client (1.25) and server (1.29) exceeds the supported minor version skew of +/-1
``` 

* OpenShift version information (if applicable):
```
Client Version: 4.12.69
Kustomize Version: v4.5.7
Kubernetes Version: v1.29.8+632b078
```

* Appsody CLI version (if applicable):
n/a

* Appsody Stack (if applicable):
n/a

So the question is - how can we prevent the service annotations ` service.kubernetes.io/topology-aware-hints` and `service.kubernetes.io/topology-mode`?

**Comment by leochr** [comment]
@hhue13 Liberty Operator doesn't currently support a configuration to disable/prevent the topology-aware annotations from being added to the Service. But you can use the `.spec.service.annotations` field in the `OpenLibertyApplication` CR to override it. Could you please try the following to see if that removes the above-specified event(s) from being fired in your cluster? Thank you.

```
  service:
    annotations:
      service.kubernetes.io/topology-aware-hints: Disabled
      service.kubernetes.io/topology-mode: Disabled
```
